name: Daily Check-in

on:
  schedule:
    - cron: "0 0,8 * * *"  # 每天 08:00 和 16:00 北京时间（UTC 0:00 和 8:00）

  workflow_dispatch:

jobs:
  run_script:
    runs-on: self-hosted
    permissions: write-all
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@main

      - name: Install python dependencies
        run: |
          pip3 install -r requirements.txt -q

      - name: Execute script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME }}
          LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
          BROWSE_ENABLED: ${{ secrets.BROWSE_ENABLED }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: |
          python3 main.py
